"""
Django settings for backend_interior project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import os
from pathlib import Path
import environ 
from django.core.exceptions import ImproperlyConfigured

# Inicializamos el lector de .env
env = environ.Env(
    # establecemos valores por defecto por si falta alguna variable (opcional)
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

def get_secret_key():
    # Buscamos la variable de entorno
    secret_key = os.environ.get('DJANGO_SECRET_KEY')
    
    # Si no existe (es None), lanzamos un error y detenemos el sistema
    if not secret_key:
        raise ImproperlyConfigured(
            "La DJANGO_SECRET_KEY no está configurada. "
            "Asegúrese de agregarla en el archivo .env o en el panel de Render."
        )
    return secret_key


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['*']





# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Apps de terceros
    'corsheaders',
    'rest_framework',
    
    # Apps 
    'api',
    'integrations',
    'catalog',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend_interior.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend_interior.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# COMENTA O BORRA ESTA PARTE PORQUE NO TIENES LA CARPETA 'static'
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]

# Configuración moderna (Reemplaza el bloque de STATICFILES_STORAGE)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        # Le quitamos la palabra 'Manifest' y borramos el OPTIONS
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage", 
    },
}
# Permite todas las fuentes (solo para desarrollo)
CORS_ALLOW_ALL_ORIGINS = True


JAZZMIN_SETTINGS = {
    # Título de la ventana del navegador
    "site_title": "Mora Mora Admin",
    # Título en la pantalla de login (puedes poner texto largo)
    "site_header": "Inversiones Mora Mora",
    # Texto de la marca arriba a la izquierda en el panel
    "site_brand": "Mora Mora Catálogo",
    # Mensaje de bienvenida en el login
    "welcome_sign": "Bienvenido al Gestor de Catálogo",
    # Copyright en el pie de página
    "copyright": "Inversiones Mora Mora Ltda",
    
    # DISEÑO DE LA BARRA LATERAL ÉPICO
    "search_model": ["catalog.Material"], # Barra de búsqueda rápida arriba
    
    #  LA MAGIA: Ocultar los modelos de usuarios y grupos de Django para el cliente
    "hide_models": ["auth.group", "auth.user"],
    
    #  Customizar los íconos del menú lateral (Usamos FontAwesome)
   "icons": {
        "catalog.Brand": "fas fa-tags",
        "catalog.Category": "fas fa-folder-open",
        "catalog.Material": "fas fa-th",
    },

    "topmenu_links": [
        {"name": "Inicio", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Gestionar Marcas", "model": "catalog.Brand", "icon": "fas fa-tags"},
        {"name": "Gestionar Categorías", "model": "catalog.Category", "icon": "fas fa-folder-open"}, 
        {"name": "Gestionar Catálogo", "model": "catalog.Material", "icon": "fas fa-th"},
    ],
    # DISEÑO EN TARJETAS PARA EL DASHBOARD CENTRAL
    "custom_links": {
        "catalog": [
            {
                "name": "Agregar Nueva Marca", 
                "url": "admin:catalog_brand_add", 
                "icon": "fas fa-plus-circle",
            },
            {
                "name": "Agregar Nuevo Material", 
                "url": "admin:catalog_material_add", 
                "icon": "fas fa-plus-circle",
            },
        ]
    },
    "changeform_format": "horizontal_tabs", 
    
    # Si quieres que dentro del formulario los botones de acción se queden fijos abajo al hacer scroll
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "collapsible"},

    # QUITAR EL ACCIONES RECIENTES (Recent Actions)
    # Cambiamos esto a False para limpiar el lado derecho del Dashboard
    "show_ui_builder": False, # Apaga el configurador en vivo si estaba activo
    
    # Esta opción oculta la columna de la derecha con los logs de modificaciones
    "changeform_format": "horizontal_tabs",
    
    # Nombres amigables para los menús
    "order_with_respect_to": ["catalog.Brand", "catalog.Material"],
    
    # Detalles visuales extra
    "show_sidebar": True,
    "navigation_expanded": True,
    "theme": "default", # Puedes cambiar a "flatly", "darkly", "cosmo", etc.
}

# Ajustes finos de colores (Opcional, para que se vea más moderno)
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark bg-dark", # Barra superior elegante en oscuro
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_options": {
        "sidebar_fixed": True, # Barra lateral se queda fija al hacer scroll
    },
    "sidebar": "sidebar-dark-primary", # Menú lateral oscuro pro
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "simplex", # Un tema limpio con tipografía bonita y espacios blancos amplios
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },

    "custom_css": "admin/css/custom_admin.css",
}