# Generated by Django 6.0.5 on 2026-05-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='catalog_image',
        ),
        migrations.RemoveField(
            model_name='material',
            name='texture_image',
        ),
        migrations.AddField(
            model_name='brand',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL del Logo'),
        ),
        migrations.AddField(
            model_name='material',
            name='catalog_image_url',
            field=models.URLField(default='', max_length=500, verbose_name='URL Imagen Catálogo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='texture_image_url',
            field=models.URLField(default='', max_length=500, verbose_name='URL Textura Limpia'),
            preserve_default=False,
        ),
    ]
